[build]
  command = "bundle install && npm run build"
  publish = "public" # Adjust this to your build output directory if different

[context.production.environment]
  RUBY_VERSION = "3.2.4"

[build.environment]
  NODE_ENV = "production"
  BUNDLE_WITHOUT = "development:test"
  POSTGRES_VERSION = "12" # or the version you need

[build.lifecycle.onbuild]
  commands = [
    "apt-get update && apt-get install -y postgresql-client libpq-dev"
  ]
